# -*- coding: utf-8 -*

import random
import re

# True if masculine, form
nouns = [
    (True, "abyssin"),
    (True, "accenteur"),
    (True, "addax"),
    (True, "agame"),
    (True, "agouti"),
    (True, "aigle"),
    (True, "akhal"),
    (True, "alligator"),
    (True, "alpaga"),
    (True, "anhinga"),
    (False, "antilope"),
    (True, "appaloosa"),
    (True, "ara"),
    (True, "argus"),
    (True, "atèle"),
    (True, "aubrac"),
    (True, "axolotl"),
    (True, "babiroussa"),
    (True, "babouin"),
    (True, "bandicoot"),
    (True, "barbican"),
    (True, "baribal"),
    (True, "barzoï"),
    (True, "basilic"),
    (True, "bateleur"),
    (True, "baudet"),
    (True, "bihoreau"),
    (True, "binturong"),
    (True, "bison"),
    (True, "blaireau"),
    (True, "boeuf"),
    (True, "boto"),
    (True, "bouledogue"),
    (True, "bouquetin"),
    (True, "bourdon"),
    (True, "bouvier"),
    (True, "boxer"),
    (True, "brochet"),
    (True, "bubale"),
    (True, "buffle"),
    (True, "butor"),
    (True, "cacatoès"),
    (True, "cachalot"),
    (True, "calao"),
    (True, "camargue"),
    (True, "campagnol"),
    (True, "caméléon"),
    (True, "canard"),
    (True, "capucin"),
    (True, "capybara"),
    (True, "caracal"),
    (True, "carcajou"),
    (True, "caribou"),
    (True, "casoar"),
    (True, "castor"),
    (True, "caïman"),
    (True, "cerf"),
    (True, "chacal"),
    (True, "chameau"),
    (True, "chamois"),
    (True, "chardonneret"),
    (True, "chat"),
    (True, "cheval"),
    (True, "chevreuil"),
    (True, "chevrotin"),
    (True, "chien"),
    (True, "chimpanzé"),
    (True, "colibri"),
    (True, "colley"),
    (True, "condor"),
    (True, "coq"),
    (True, "coque"),
    (True, "corbeau"),
    (True, "cormoran"),
    (True, "coucou"),
    (True, "coyote"),
    (True, "crapaud"),
    (True, "crevette"),
    (True, "crocodile"),
    (True, "cygne"),
    (True, "daim"),
    (True, "dalmatien"),
    (True, "daman"),
    (True, "dauphin"),
    (True, "dindon"),
    (True, "dingo"),
    (True, "dodo"),
    (True, "dogue"),
    (True, "doryphore"),
    (True, "douc"),
    (True, "dragon"),
    (True, "dromadaire"),
    (True, "ecureuil"),
    (True, "eider"),
    (True, "elan"),
    (True, "elephant"),
    (True, "emeu"),
    (True, "entelle"),
    (True, "escargot"),
    (True, "etourneau"),
    (True, "faisan"),
    (True, "faucon"),
    (True, "fennec"),
    (True, "flamantrose"),
    (True, "frelon"),
    (True, "frison"),
    (True, "gavial"),
    (True, "geai"),
    (True, "gecko"),
    (True, "gerenuk"),
    (True, "gibbon"),
    (True, "glouton"),
    (True, "gnou"),
    (True, "gorille"),
    (True, "goujon"),
    (True, "goéland"),
    (True, "grillon"),
    (True, "guanaco"),
    (True, "guépard"),
    (True, "haflinger"),
    (True, "hamster"),
    (True, "harfang"),
    (True, "henson"),
    (True, "hippopotame"),
    (True, "hoazin"),
    (False, "hyène"),
    (True, "hérisson"),
    (True, "héron"),
    (True, "ibijau"),
    (True, "ibis"),
    (True, "iguane"),
    (True, "impala"),
    (True, "indri"),
    (True, "jabiru"),
    (True, "jacamar"),
    (True, "jaguar"),
    (True, "jaguarondi"),
    (True, "kangourou"),
    (True, "kakapo"),
    (True, "kiwi"),
    (True, "koala"),
    (True, "lagopède"),
    (True, "lama"),
    (True, "lamantin"),
    (True, "langur"),
    (True, "lapin"),
    (True, "leonberg"),
    (True, "lion"),
    (True, "lipizzan"),
    (True, "lièvre"),
    (True, "loir"),
    (True, "loriquet"),
    (True, "loup"),
    (True, "lucane"),
    (True, "lycaon"),
    (True, "lynx"),
    (True, "léopard"),
    (True, "lérot"),
    (True, "lézard"),
    (True, "macaque"),
    (True, "macareux"),
    (True, "machaon"),
    (True, "maki"),
    (True, "mammouth"),
    (True, "manchot"),
    (True, "mandrill"),
    (True, "manul"),
    (True, "mara"),
    (True, "marabout"),
    (True, "margay"),
    (True, "markhor"),
    (True, "merle"),
    (True, "milan"),
    (True, "moloch"),
    (True, "monarque"),
    (True, "morse"),
    (True, "motmot"),
    (True, "mouflon"),
    (True, "mouton"),
    (True, "mulot"),
    (True, "muntjac"),
    (True, "muscardin"),
    (True, "myrmidon"),
    (True, "narval"),
    (True, "nasique"),
    (True, "numbat"),
    (True, "nyala"),
    (True, "ocelot"),
    (True, "okapi"),
    (True, "olinguito"),
    (True, "opossum"),
    (True, "orangoutan"),
    (True, "orignal"),
    (True, "ornithorynque"),
    (True, "orque"),
    (True, "orvet"),
    (True, "oryctérope"),
    (True, "oryx"),
    (True, "otocyon"),
    (True, "ouakari"),
    (True, "ouandérou"),
    (True, "ouaouaron"),
    (True, "ouistiti"),
    (True, "ours"),
    (True, "panda"),
    (True, "pangolin"),
    (True, "paon"),
    (True, "paresseux"),
    (True, "percheron"),
    (True, "phasme"),
    (True, "phoque"),
    (True, "picvert"),
    (True, "pinson"),
    (True, "pièride"),
    (True, "poisson"),
    (True, "porc"),
    (True, "porcepic"),
    (True, "puma"),
    (True, "putois"),
    (True, "pygargue"),
    (True, "pécari"),
    (True, "pélican"),
    (True, "ragondin"),
    (True, "raton"),
    (True, "renard"),
    (True, "renne"),
    (True, "requin"),
    (True, "rhinocéros"),
    (True, "saki"),
    (True, "samoyède"),
    (True, "sanglier"),
    (True, "serpentaire"),
    (True, "serval"),
    (True, "siamois"),
    (True, "silure"),
    (True, "singe"),
    (True, "sizerin"),
    (True, "smilodon"),
    (True, "sphynx"),
    (True, "springbok"),
    (True, "steenbok"),
    (True, "suricate"),
    (True, "takin"),
    (True, "tamandua"),
    (True, "tamanoir"),
    (True, "tamarin"),
    (True, "tantale"),
    (True, "tapir"),
    (True, "tarier"),
    (True, "tarsier"),
    (True, "tatou"),
    (True, "tchitrec"),
    (True, "tenrec"),
    (True, "thon"),
    (True, "tigre"),
    (True, "tisserin"),
    (True, "topi"),
    (True, "toucan"),
    (True, "touraco"),
    (True, "triton"),
    (True, "trogon"),
    (True, "tyrannosaure"),
    (True, "tétras"),
    (True, "unau"),
    (True, "varan"),
    (True, "vautour"),
    (True, "ver"),
    (True, "viscache"),
    (True, "vison"),
    (True, "wallaby"),
    (True, "wapiti"),
    (True, "wombat"),
    (True, "xylocope"),
    (True, "yack"),
    (True, "yapock"),
    (True, "yorkshire"),
    (True, "zèbre"),
    (False, "abeille"),
    (False, "aigrette"),
    (False, "alouette"),
    (False, "argiope"),
    (False, "autruche"),
    (False, "baleine"),
    (False, "belette"),
    (False, "bergeronnette"),
    (False, "bernache"),
    (False, "buse"),
    (False, "béluga"),
    (False, "caille"),
    (False, "chauvesouris"),
    (False, "chouette"),
    (False, "chèvre"),
    (False, "cigale"),
    (False, "cigogne"),
    (False, "circaète"),
    (False, "civette"),
    (False, "coccinelle"),
    (False, "corneille"),
    (False, "couleuvre"),
    (False, "cétoine"),
    (False, "dasyure"),
    (False, "échasse"),
    (False, "fauvette"),
    (False, "fouine"),
    (False, "fourmi"),
    (False, "gazelle"),
    (False, "genette"),
    (False, "girafe"),
    (False, "grenouille"),
    (False, "grue"),
    (False, "guêpe"),
    (False, "gypaète"),
    (False, "harpie"),
    (False, "hermine"),
    (False, "hirondelle"),
    (False, "huitre"),
    (False, "hydropote"),
    (False, "jument"),
    (False, "libellule"),
    (False, "linotte"),
    (False, "loutre"),
    (False, "malamute"),
    (False, "mamba"),
    (False, "mangouste"),
    (False, "mante"),
    (False, "marmotte"),
    (False, "martre"),
    (False, "morue"),
    (False, "mouche"),
    (False, "moucherolle"),
    (False, "mouffette"),
    (False, "moule"),
    (False, "musaraigne"),
    (False, "mésange"),
    (False, "nyctale"),
    (False, "ombrette"),
    (False, "oriole"),
    (False, "otarie"),
    (False, "pacarana"),
    (False, "panthère"),
    (False, "panure"),
    (False, "paruline"),
    (False, "perche"),
    (False, "perruche"),
    (True, "pétrogale"),
    (False, "phacochère"),
    (False, "pie"),
    (False, "pintade"),
    (False, "pirolle"),
    (False, "potamochère"),
    (False, "poule"),
    (False, "quokka"),
    (False, "raie"),
    (False, "rougegorge"),
    (False, "rougequeue"),
    (False, "salamandre"),
    (False, "sauterelle"),
    (False, "sittelle"),
    (False, "souris"),
    (False, "spizaète"),
    (False, "tamia"),
    (False, "tanche"),
    (False, "tarentaise"),
    (False, "tarine"),
    (False, "taupe"),
    (False, "tortue"),
    (False, "truite"),
    (False, "vigogne"),
    (False, "vipère"),
    (False, "viscache")
]

adjs = [
    (False, "accueillant", "accueillante"),
    (False, "adorable", "adorable"),
    (False, "alourdi", "alourdie"),
    (False, "attifé", "attifée"),
    (False, "attrayant", "attrayante"),
    (True, "beau/bel", "belle"),
    (False, "carré", "carrée"),
    (False, "confiant", "confiante"),
    (False, "costaud", "costaude"),
    (False, "crasseux", "crasseuse"),
    (False, "désillusionné", "désillusionnée"),
    (False, "dynamique", "dynamique"),
    (False, "élégant", "élégante"),
    (False, "élevé", "élevée"),
    (False, "énervé", "énervée"),
    (False, "gai", "gaie"),
    (True, "gentil", "gentille"),
    (True, "gros", "grose"),
    (False, "habillé", "habillée"),
    (False, "hideux", "hideuse"),
    (False, "hirsute", "hirsute"),
    (False, "inquiet", "inquiète"),
    (False, "magnifique", "magnifique"),
    (True, "maigre", "maigre"),
    (False, "maladroit", "maladroite"),
    (False, "merveilleux", "merveilleuse"),
    (False, "mince", "mince"),
    (False, "nerveux", "nerveuse"),
    (False, "offensé", "offensée"),
    (False, "parfait", "parfaite"),
    (False, "plaisant", "plaisante"),
    (False, "propre", "propre"),
    (False, "impeccable", "impeccable"),
    (False, "méticuleux", "méticuleux"),
    (False, "pimpant", "pimpante"),
    (False, "raffiné", "raffinée"),
    (False, "présentable", "présentable"),
    (False, "soigneux", "soigneuse"),
    (False, "chic", "chic"),
    (False, "convenable", "convenable"),
    (False, "ravissant", "ravissante"),
    (False, "réfléchi", "réfléchie"),
    (False, "sale", "sale"),
    (False, "sauvage", "sauvage"),
    (False, "séduisant", "séduisante"),
    (False, "snob", "snob"),
    (False, "sombre", "sombre"),
    (False, "souriant", "souriante"),
    (False, "splendide", "splendide"),
    (False, "svelte", "svelte"),
    (False, "tendu", "tendue"),
    (False, "terne", "terne"),
    (False, "timide", "timide"),
    (False, "trompeur", "trompeuse"),
    (False, "vif", "vive"),
    (False, "vivace", "vivace"),
    (False, "agressif", "agressive"),
    (False, "ambitieux", "ambitieuse"),
    (False, "amusant", "amusante"),
    (False, "amusé", "amusée"),
    (False, "avare", "avare"),
    (False, "brave", "brave"),
    (False, "brillant", "brillante"),
    (False, "chaleureux", "chaleureuse"),
    (False, "combatif", "combative"),
    (False, "coopératif", "coopérative"),
    (False, "cruel", "cruelle"),
    (False, "dangereux", "dangereuse"),
    (False, "désagréable", "désagréable"),
    (False, "déterminé", "déterminée"),
    (False, "diligent", "diligente"),
    (False, "dominant", "dominante"),
    (False, "doué", "douée"),
    (False, "égoïste", "égoïste"),
    (False, "entraînant", "entraînante"),
    (False, "farfelu", "farfelue"),
    (False, "fatigant", "fatigante"),
    (False, "franc", "franche"),
    (False, "généreux", "généreuse"),
    (False, "harmonieux", "harmonieuse"),
    (False, "hésitant", "hésitante"),
    (False, "impartial", "impartiale"),
    (False, "informé", "informée"),
    (False, "instinctif", "instinctive"),
    (False, "intrépide", "intrépide"),
    (False, "succinct", "succincte"),
    (False, "bref", "brève"),
    (False, "véloce", "véloce"),
    (False, "fugitif", "fugitive"),
    (False, "furtif", "furtive"),
    (False, "ailé", "ailée"),
    (False, "poilu", "poilue"),
    (False, "chauve", "chauve"),
    (False, "imberbe", "imberbe"),
    (False, "courageux", "courageuse"),
    (False, "jaloux", "jalouse"),
    (False, "lâche", "lâche"),
    (False, "loufoque", "loufoque"),
    (False, "mystérieux", "mystérieuse"),
    (False, "placide", "placide"),
    (False, "ponctuel", "ponctuelle"),
    (False, "posé", "posée"),
    (False, "protecteur", "protecteure"),
    (False, "regardant", "regardante"),
    (False, "sage", "sage"),
    (False, "scélérat", "scélérate"),
    (False, "serviable", "serviable"),
    (False, "sincère", "sincère"),
    (False, "talentueux", "talentueuse"),
    (False, "truculent", "truculente"),
    (False, "vorace", "vorace"),
    (False, "amoureux", "amoureuse"),
    (False, "anxieux", "anxieuse"),
    (True, "beau", "belle"),
    (False, "bourru", "bourrue"),
    (False, "calme", "calme"),
    (False, "choqué", "choquée"),
    (False, "coquin", "coquine"),
    (False, "coupable", "coupable"),
    (False, "débordé", "débordée"),
    (False, "dégoûté", "dégoûtée"),
    (False, "déprimé", "déprimée"),
    (False, "dérangé", "dérangée"),
    (False, "douloureux", "douloureuse"),
    (False, "effrayé", "effrayée"),
    (False, "ennuyé", "ennuyée"),
    (False, "envieux", "envieuse"),
    (False, "épuisé", "épuisée"),
    (False, "exaspéré", "exaspérée"),
    (False, "extatique", "extatique"),
    (False, "fâché", "fâchée"),
    (False, "fatigué", "fatiguée"),
    (True, "faux", "fausse"),
    (False, "fidèle", "fidèle"),
    (False, "fier", "fière"),
    (False, "frustré", "frustrée"),
    (False, "gêné", "gênée"),
    (False, "gentil", "gentille"),
    (False, "heureux", "heureuse"),
    (False, "horrible", "horrible"),
    (False, "indisposé", "indisposée"),
    (False, "jovial", "joviale"),
    (False, "joyeux", "joyeuse"),
    (False, "las", "lasse"),
    (False, "malade", "malade"),
    (False, "malicieux", "malicieuse"),
    (False, "mature", "mature"),
    (False, "mauvais", "mauvaise"),
    (False, "méchant", "méchante"),
    (False, "pacifique", "pacifique"),
    (False, "peiné", "peinée"),
    (False, "perplexe", "perplexe"),
    (False, "perturbé", "perturbée"),
    (False, "prétentieux", "prétentieuse"),
    (False, "prudent", "prudente"),
    (False, "rieur", "rieuse"),
    (False, "solitaire", "solitaire"),
    (False, "soucieux", "soucieuse"),
    (False, "souffrant", "souffrante"),
    (False, "soupçonneux", "soupçonneuse"),
    (False, "sûr", "sûre"),
    (False, "discret", "discrète"),
    (False, "tranquille", "tranquille"),
    (False, "triste", "triste"),
    (False, "troublé", "troublée"),
    (False, "altéré", "altérée"),
    (False, "circulaire", "circulaire"),
    (False, "creux", "creuse"),
    (False, "décomposé", "décomposée"),
    (False, "déformé", "déformée"),
    (False, "droit", "droite"),
    (False, "étroit", "étroite"),
    (False, "géométrique", "géométrique"),
    (True, "long", "longue"),
    (False, "maigre", "maigre"),
    (False, "plat", "plate"),
    (False, "primitif", "primitive"),
    (False, "raide", "raide"),
    (False, "rectangulaire", "rectangulaire"),
    (False, "rond", "ronde"),
    (False, "simple", "simple"),
    (False, "tordu", "tordue"),
    (False, "triangulaire", "triangulaire"),
    (True, "vaste", "vaste"),
    (False, "colossal", "colossale"),
    (False, "énorme", "énorme"),
    (False, "exigu", "exigue"),
    (False, "fin", "fine"),
    (False, "gigantesque", "gigantesque"),
    (True, "grand", "grande"),
    (True, "immense", "immense"),
    (False, "important", "importante"),
    (False, "imposant", "imposante"),
    (False, "infime", "infime"),
    (True, "large", "large"),
    (False, "menu", "menue"),
    (True, "minuscule", "minuscule"),
    (False, "monumental", "monumentale"),
    (True, "petit", "petite"),
    (True, "chouette", "chouette"),
    (True, "super", "super"),
    (False, "vaste", "vaste"),
    (False, "actuel", "actuelle"),
    (False, "ancien", "ancienne"),
    (False, "annuel", "annuelle"),
    (False, "antique", "antique"),
    (False, "avancé", "avancée"),
    (False, "contemporain", "contemporaine"),
    (False, "hebdomadaire", "hebdomadaire"),
    (True, "jeune", "jeune"),
    (False, "journalier", "journalière"),
    (False, "lent", "lente"),
    (False, "mensuel", "mensuelle"),
    (False, "moderne", "moderne"),
    (False, "neuf", "neuve"),
    (False, "nouveau", "nouvelle"),
    (False, "précipité", "précipitée"),
    (False, "précis", "précise"),
    (False, "idoine", "idoine"),
    (False, "prompt", "prompte"),
    (False, "quotidien", "quotidienne"),
    (False, "rapide", "rapide"),
    (False, "alerte", "alerte"),
    (False, "preste", "preste"),
    (False, "récent", "récente"),
    (False, "séculaire", "séculaire"),
    (False, "tardif", "tardive"),
    (False, "trimestriel", "trimestrielle"),
    (False, "vétuste", "vétuste"),
    (True, "vieux/vieil", "vieille"),
    (False, "abondant", "abondante"),
    (False, "bienfaisant", "bienfaisante"),
    (False, "chargé", "chargée"),
    (False, "compact", "compacte"),
    (False, "considérable", "considérable"),
    (False, "dense", "dense"),
    (False, "écrasant", "écrasante"),
    (True, "énorme", "énorme"),
    (True, "extra", "extra"),
    (False, "fréquent", "fréquente"),
    (True, "gros", "grosse"),
    (False, "illimité", "illimitée"),
    (False, "incalculable", "incalculable"),
    (False, "léger", "légère"),
    (True, "lourd", "lourde"),
    (False, "multiple", "multiple"),
    (False, "rempli", "remplie"),
    (False, "substantiel", "substantielle"),
    (False, "répété", "répétée"),
    (False, "vide", "vide"),
    (False, "volumineux", "volumineuse"),
    (False, "argenté", "argentée"),
    (False, "azuré", "azuré"),
    (False, "blanc", "blanche"),
    (False, "bleu", "bleue"),
    (False, "blond", "blonde"),
    (False, "brun", "brune"),
    (False, "châtain", "châtaine"),
    (False, "cyan", "cyan"),
    (False, "grenat", "grenat"),
    (False, "magenta", "magenta"),
    (False, "marron", "marron"),
    (False, "noir", "noire"),
    (False, "orange", "orange"),
    (False, "pourpré", "pourprée"),
    (False, "rose", "rose"),
    (False, "roux", "rousse"),
    (False, "turquoise", "turquoise"),
    (False, "vert", "verte"),
    (False, "violet", "violette"),

    (False, "multilingue", "multilingue"),
    (False, "bilingue", "bilingue"),
    (False, "plurilingue", "plurilingue"),
    (False, "polyglotte", "polyglotte"),
    (False, "érudit", "érudite"),
    (False, "savant", "savante"),
    (False, "philosophe", "philosophe"),
    (False, "studieux", "studieuse"),
    (False, "instruit", "instruite"),
    (False, "lettré", "lettrée"),
    (False, "cultivé", "cultivée"),
    (False, "clairvoyant", "clairvoyante"),
    (False, "expert", "experte"),
    (False, "ingénieux", "ingénieuse"),
    (False, "compétent", "compétente"),
    (False, "scientifique", "scientifique"),
    (False, "chercheur", "chercheuse"),
    (False, "spécialiste", "spécialiste"),
    (False, "humaniste", "humaniste"),
    (True, "maître", "maîtresse"),
    (False, "câlé", "câlée"),
    (False, "intelligent", "intelligente"),
    (False, "averti", "avertie"),
    (False, "fortiche", "fortiche"),
    (False, "habile", "habile"),
    (False, "travailleur", "travailleuse"),
    (False, "drôle", "drôle"),
    (False, "égayant", "égayant"),
    (False, "drôlet", "drôlette"),
    (False, "cocasse", "cocasse"),
    (False, "désopilant", "désopilant"),
    (False, "facétieux", "facétieuse"),
    (False, "marrant", "marrante"),
    (False, "tordant", "tordante"),
    (False, "comique", "comique"),
    (False, "farfelu", "farfelue"),
    (False, "spirituel", "spirituelle"),
    (False, "insolite", "insolite"),
    (False, "bizarre", "bizarre"),
    (True, "étrange", "étrange"),
    (False, "curieux", "curieuse"),
    (False, "docte", "docte"),
    (False, "juste", "juste"),
    (False, "paisible", "paisible"),
    (False, "sagace", "sagace"),
    (False, "ascète", "ascète"),
    (False, "honnête", "honnête"),
    (True, "honnête", "honnête")

]


def CapitalizeASCII(word):
    word = word.replace("é", "e").replace("è", "e").replace("ê", "e")
    word = word.replace("û", "u").replace("î", "i").replace("ï", "i").replace("â", "a")
    word = word.replace("ç", "c")
    return word[:1].upper()+word[1:]


def generate_name_fr(length=15):
    while True:
        gender, noun = random.choice(nouns)
        left, adj_m, adj_f = random.choice(adjs)
        if gender:
            adj = adj_m
        else:
            adj = adj_f
        # don't convert end-é into e - too ambiguous to read
        if adj.endswith("é"):
            continue
        adj = CapitalizeASCII(adj)
        noun = CapitalizeASCII(noun)
        if left:
            adj_forms = adj.split("/")
            if len(adj_forms) == 2:
                if re.match(r"^[AEIOUH]", noun):
                    adj = CapitalizeASCII(adj_forms[1])
                else:
                    adj = adj_forms[0]
            name = adj + noun
        else:
            name = noun + adj
        if len(name) <= length and re.match(r"[A-Z][a-z]+[A-Z][a-z]+$", name):
            return name


if __name__ == "__main__":
    for i in range(100):
        print generate_name_fr()
